`timescale 1ns/1ps

module svt_tb;
    reg clk;
    reg rst_n;

    // Processor Instantiation
    rv32i_multi_cycle rv (
        .clk(clk),
        .rst_n(rst_n)
    );

    // Expected Values Arrays
    reg [31:0] expected_regs [0:31];
    reg [31:0] expected_mem  [0:15];
    reg [31:0] expected_pc   [0:0];

    // Clock Generation
    always #5 clk = ~clk;

    integer i;
    integer errors;

    initial begin
        $dumpfile("SVT_verification.vcd");
        $dumpvars(0, svt_tb);
        
        // Load expected hex files generated by Python golden model
        $readmemh("tb/expected_regs.hex", expected_regs);
        $readmemh("tb/expected_mem.hex", expected_mem);
        $readmemh("tb/expected_pc.hex", expected_pc);

        errors = 0;
        clk = 0;
        rst_n = 0;
        
        #10;
        rst_n = 1;
        
        // Wait sufficient time for multi-cycle execution
        // Each instruction takes 3-5 cycles (30-50ns). 200 instructions ≈ 8000ns
        #8000;
        
        $display("\n=======================================================");
        $display("          SOFTWARE VERIFICATION TESTBENCH (SVT)          ");
        $display("=======================================================\n");

        // Check PC
        if (rv.PC !== expected_pc[0]) begin
            $display("[FAIL] PC Mismatch! Expected: %08x, Actual: %08x", expected_pc[0], rv.PC);
            errors = errors + 1;
        end else begin
            $display("[PASS] PC matches: %08x", rv.PC);
        end

        // Check Registers
        $display("\n--- Register Checks ---");
        for (i = 0; i < 32; i = i + 1) begin
            if (rv.rf.regs[i] !== expected_regs[i]) begin
                $display("[FAIL] Reg x%0d Mismatch! Expected: %08x, Actual: %08x", i, expected_regs[i], rv.rf.regs[i]);
                errors = errors + 1;
            end
        end
        if (errors == 0) $display("[PASS] All 32 Registers match expected values!");

        // Check Memory (First 16 words)
        $display("\n--- Memory Checks ---");
        for (i = 0; i < 16; i = i + 1) begin
            if (expected_mem[i] === 32'hxxxxxxxx && rv.dm.memory[i] === 32'hxxxxxxxx) begin
                // Both uninitialized — skip
            end else if (rv.dm.memory[i] !== expected_mem[i]) begin
                $display("[FAIL] Mem[%0d] Mismatch! Expected: %08x, Actual: %08x", i, expected_mem[i], rv.dm.memory[i]);
                errors = errors + 1;
            end
        end
        if (errors == 0) $display("[PASS] Memory entries match expected values!");

        $display("\n=======================================================");
        if (errors == 0) begin
            $display("                    [SVT PASS]                         ");
        end else begin
            $display("         [SVT FAIL] - Found %0d mismatches!            ", errors);
        end
        $display("=======================================================\n");

        $finish;
    end
endmodule
